application: chirpradio-hrd
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /api/.*
  script: api.handler.application

# -----------------------------------------------------------------------
# NOTE: see settings.PUBLIC_TOP_LEVEL_URLS for non-login protected pages.
# -----------------------------------------------------------------------

- url: /favicon\.ico
  static_files: media/common/img/favicon.ico
  upload: media/common/img/favicon\.ico

# Serve static media.  Note that everything under media is world-readable!
# Making cache expiration more agressive until CDN pushes is fixed:
# http://code.google.com/p/googleappengine/issues/detail?id=6549
- url: /media
  static_dir: media
  expiration: 30m

# restrict public access to playlist task queue URL handlers
- url: /playlists/task/.*
  script: main.application
  login: admin

# restrict public access to auth task queue URL handlers
- url: /auth/task/.*
  script: main.application
  login: admin

# For everything else, we always want to use HTTPS.
- url: /.*
  secure: always
  script: main.application


inbound_services:
- warmup


builtins:
- remote_api: on


libraries:
- name: django
  version: "1.3"
- name: webapp2
  version: latest
- name: pycrypto
  version: latest


env_variables:
  DJANGO_SETTINGS_MODULE: 'settings'


skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.bak$
- devlib/.*
- docs/.*
